import localFont from 'next/font/local'
import type {Metadata} from 'next'
import './globals.css'

const Circe = localFont({
  src: [
    {
      path: '../assets/fonts/Circe-Light.woff',
      weight: '300',
    },
    {
      path: '../assets/fonts/Circe-Regular.woff',
      weight: '400',
    },
    {
      path: '../assets/fonts/Circe-Bold.woff',
      weight: '700',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={`${Circe.className} antialiased`}>{children}</body>
    </html>
  )
}
